numpy  
자료형 list와 비슷, 더 빠르고 메모리를 효율적으로 관리  
반복문없이 데이터 배열에 대한 처리를 지원  
데이터 과학 도구에 대한 생태계의 핵심   

In [1]:
import numpy as np

1차원, 2차원 3차원  
axis 0 ,1 2차원  
axis 0,1 ,2 3차원  

In [6]:
a1 = np.array([1,2,3,4,5])
print(a1)

print(type(a1)) #ndarray라는 객체이다. 
print(a1.shape) # 5개의 element가 있구나, 1차원 배열이구나 
print(a1[0],a1[1],a1[2],a1[3],a1[4])
a1[0] = 4
a1[1]=5
a1[2]=6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [9]:
a2 = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(a2)
print(a2.shape) #(3,3)의 array임을 알 수있다. 
print(a2[0,0],a2[1,1],a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [13]:
a3 = np.array([ [ [1,2,3], [4,5,6], [7,8,9] ],
                [ [1,2,3], [4,5,6], [7,8,9] ],
                [ [1,2,3], [4,5,6], [7,8,9] ] ])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


배열 생성 및 초기화  
zeros() : 모든 요소를 0으로 초기화  

In [14]:
np.zeros(10) #10개의 요소를 0으로 채운 배열 선언

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones((3,3)) #2차원 형태의 모두 1로 채워진 배열

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.full((3,3), fill_value=1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

eye() : 단위행렬(identity method)생성  
주대각선의 원소가 모두 1이고, 나머지 원소는 모두 0인 정사각 행렬  

In [19]:
np.eye(3)  #단위 행렬은 정사각 행렬이므로, 크기만 지정해주면 된다. 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

tri() : 삼각행렬 생성

In [20]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

empty() : 초기화되지 않은 배열 생성  
초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음.  

In [22]:
np.empty(10) #생성되는 배열에 어떤값이 올지 모르기에 주의해야환다. 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

_like() :지정된 배열과 shape가 같은 행렬 생성  
np.zeros_like()  
np.ones_like()  
np.full_like()  
np.empty_like()  과 같음  


In [23]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [24]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
print(a3)
np.full_like(a3 , 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

생성한 값으로 배열 생성  
어떤 값을 생성하고 그 값을 가지고 배열을 생성하는 것.  

In [26]:
#arange() :정수 범위로 배열 생성
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [27]:
#np.linspace() :범위내에서 균등한 간격으로 배열 생성
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
#logspace() : 범위 내에서 균등간격으로 로그 스케일로 배열 생성
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

랜덤값으로 배열 생성

In [31]:
#random.random() : 랜덤한 수의 배열 생성 , 실수값으로 
np.random.random((3,3))

array([[0.39494616, 0.50841778, 0.2606716 ],
       [0.0607984 , 0.78608491, 0.97150125],
       [0.24260684, 0.73451648, 0.75638007]])

In [32]:
#np.random.randint() : 전수 랜덤 배열 생성
np.random.randint(0,10,(3,3)) # 0~10까지 중

array([[4, 4, 6],
       [7, 7, 7],
       [0, 7, 1]])

In [33]:
#random.normal() : 정규분표를 고려한 랜덤한 수의 배열 생성
#평균 = 0, 표준편차 = 1, (3,3)배열 생성 예시 
np.random.normal(0,1,(3,3))

array([[ 2.38136703, -2.25663425,  0.61584171],
       [ 0.43970389, -0.13190584,  0.0712889 ],
       [ 0.48728696,  0.06716683, -1.77836521]])

In [37]:
#random.rand() :균등분표
np.random.rand(3,3)

array([[0.60388386, 0.83612886, 0.83815802],
       [0.55169489, 0.6319693 , 0.3280271 ],
       [0.59663753, 0.18300242, 0.99032922]])

In [38]:
#random.randn() : 표준 정규분포를 고려한 랜덤수의 배열 생성
np.random.randn(3,3)

array([[-1.35402874,  0.10705625,  0.6570587 ],
       [ 0.58712725, -0.838064  , -0.78515115],
       [-2.32372961, -0.33326742, -0.23160433]])

표준 데이터 타입  
dtype의 종류

In [40]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
np.ones((3,3),dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [42]:
np.full((3,3),fill_value=1.0,dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

날짜 시간 배열 생성  

In [44]:
date = np.array('2020-01-01',dtype = np.datetime64 ) #날짜 시간을 나타내게 하는 type이다. 
date

array('2020-01-01', dtype='datetime64[D]')

In [45]:
date + np.arange(12) #arange에서 생성된 값을 기존 날짜에 추가된 형태로 변환해주기도 한다. 

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [46]:
datetime = np.datetime64('2020-06-01 12:00')
datetime #T라는 대문자 다음에 12:00이라고 표현된다. 

numpy.datetime64('2020-06-01T12:00')

In [47]:
datetime = np.datetime64('2020-06-01 12:00:12.34','ns')
datetime #ns까지 표현한 저장이 이루어지기도 한다. 

numpy.datetime64('2020-06-01T12:00:12.340000000')

배열 조회  

In [50]:
def array_info(array):
    print(array)
    print("ndim : ",array.ndim) #차원 수를 의미한다. 
    print("shape : ", array.shape)
    print("dtype :",array.dtype)
    print("size : ",array.size)
    print("itemsize : ",array.itemsize) #하나의 요소가 가즌 데이터 크기 
    print("nbytes : ",array.nbytes)
    print("strides : ",array.strides) # 하나의 요소로 넘어가는데에 필요한 데이터의 크기를 의미한다. 

In [51]:
array_info(a1)

[4 5 6 4 5]
ndim :  1
shape :  (5,)
dtype : int32
size :  5
itemsize :  4
nbytes :  20
strides :  (4,)


In [52]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim :  2
shape :  (3, 3)
dtype : int32
size :  9
itemsize :  4
nbytes :  36
strides :  (12, 4)


In [53]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim :  3
shape :  (3, 3, 3)
dtype : int32
size :  27
itemsize :  4
nbytes :  108
strides :  (36, 12, 4)


인덱싱

In [59]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [61]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [63]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


슬라이싱

In [65]:
#슬라이싱 구문 a[start:stop:step], 기본값 start = 0, stop = ndim, step = 1
print(a1)
print(a1[0:2]) #2는 카운트 하지 않는다. 
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [66]:
print(a2)
print(a2[1])
print(a2[1,:])
print(a2[:2, :2])
print(a2[1:,::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


불리언 인덱싱  

True 값인 인덱스의 값만 조회

In [69]:
print(a1)
bi = [False, True,True,False,True]
print(a1[bi]) #True인 인덱스 위치만 프린트해준다. 
bi = [True,False,True,True,False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [71]:
print(a2)
bi = np.random.randint(0,2,(3,3),dtype=bool) #0,1의 두 가지 값중에서 랜덤으로 선택한다.
print(bi)
print(a2[bi])
#특정 조건을 만족하는 값만 받아오기를 원할때 불리언 읻겡싱을 많이 사용하게 된다.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False  True]
 [ True False False]
 [ True  True False]]
[3 4 7 8]


팬시 인덱싱

In [75]:
print(a1)
print(a1[0],a1[2])
ind = [0,2]
print(a1[ind]) #인덱스를 묶어서 한번에 전달해준다. 
ind = np.array([[0,1],
                [2,0] ])

print(a1[ind]) #인덱스가 이차원으로 선언된다면, a1이 일차원이어도 이차원 배열로 선언된다. 

[4 5 6 4 5]
4 6
[4 6]
[[4 5]
 [6 4]]


In [77]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row,col]) #(0,1). (2,2)의 위치에 존재하는 인덱스의 값을 추출한다. 

print(a2[row, :])
print(a2[: , col])
print(a2[2,col])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[8 9]
[[5 6]
 [8 9]]


배열 값 삽입/수정/삭제/복사

In [80]:
#배열 값 삽입
#insert() : 배열의 특정 위치에 값 삽입
#axis를 지정하지 않으면 1차원 배열로 변환
#추가할 방향을 axis로 지정
#원본 배열 변경없이 새로운 뱌열 반환
print(a1)
b1 = np.insert(a1,obj = 0,values=10)
print(b1)
print(a1)
c1 = np.insert(a1,2,10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[4 5 6 4 5]
[ 4  5 10  6  4  5]


In [82]:
print(a2)
b2 = np.insert(a2 , obj = 1, values=10,axis=0) #axis가 0인 것의 10을 1번째에 추가
print(b2)
c2 = np.insert(a2,1,10,axis = 1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


In [86]:
#배열 값 수정  
#배열의 인덱싱으로 접근하여 값 수정
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)

a1[:1] = 9
print(a1)

i = np.array([1,3,4])
a1[i] = 0
print(a1)

a1[i] += 4
print(a1)

[9 0 3 0 0]
[1 2 3 0 0]
[9 2 3 0 0]
[9 0 3 0 0]
[9 4 3 4 4]


In [90]:
print(a2)
a2[0,0] = 1
a2[1,1] = 2
a2[2,2] = 3
a2[0] = 1
print(a2)

a2[1:,2] = 9
print(a2)

row = np.array([0,1])
col = np.array([1,2])
a2[row,col] = 0
print(a2)

[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 1 1]
 [4 2 9]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


In [92]:
#배열 값 삭제
#delete() : 배열의 특정 위치에 값 삭제
#원본 배열 변경없이 새로운 배열 반환
print(a1)
b1 = np.delete(a1,1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [94]:
print(a2)
b2 = np.delete(a2 , 1 , axis = 0)
print(b2)
print(a2)

c2 = np.delete(a2,1,axis = 1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


In [98]:
#배열 복사
#리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님.
print(a2)
print(a2[:2 , :2])
a2_sub = a2[:2,:2]
print(a2_sub)

a2_sub[:,1] = 0
print(a2_sub)
print(a2)
#원본 배열이 유지되는 상태에서 사용되기 때문에

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


In [99]:
#copy() : 배열이나 하위 배열 내의 값을 복사한다. 동일한 메모리 위치 사용 X
print(a2)
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1] = 1
print(a2_sub_copy)
print(a2)
#copy된 것과 a2는 서로 별개의 위치에 있다. 

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


배열 변환


In [101]:
#배열 전치 및 축 변경
print(a2)
print(a2.T) #행과 열의 축이 변경된다 Transpose

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [102]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [103]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [104]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2)) #어떤 축을 스왑할지 선택할 수 있다. 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


In [105]:
#배열 재구조화
#reshape() : 배열의 형상을 변경
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [106]:
#newaxis() : 새로운 축 추가
print(n1)
print(n1[np.newaxis,:5])
print(n1[:5,np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


배열 크기 변경

In [112]:
n2 = np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2)) #배열의 모양을 변경 시킨다. 
print(n2)

[[8 5 7 8 5]
 [4 7 5 4 9]]
[[8 5]
 [7 8]
 [5 4]
 [7 5]
 [4 9]]


In [118]:
#배열 크기 증가
#빈 공간은 0으로 채운다. 
n2.resize((5,5),refcheck=False)
print(n2)

[[8 5 7 8 5]
 [4 7 5 4 9]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [120]:
#배열 크기 감소
#포함되지 않은 값은 삭제됨
n2.resize((3,3),refcheck=False)
print(n2)

[[8 5 7]
 [8 5 4]
 [7 5 4]]


In [121]:
#배열 추가 
#append() : 배열의 끝에 값 추가 
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [122]:
#axis 지정이 없으면 1차원 배열 형태로 변형되어 결합된다. 
c2 = np.append(a2,b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [127]:
#axis를 0으로 지정
#shape[0]를 제외한 나머지 shape는 같아야 한다. 
c2 = np.append(a2,b2,axis = 0)
print(c2)
c2 = np.append(a2,b2,axis=1)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [128]:
#배열 연결
#concatenate() : 튜플이나 배열의 리스트를 인수로 사용해 배열 연결
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [129]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [131]:
a2 = np.array([[1,2,3],
                [4,5,6]])
np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [132]:
a2 = np.array([[1,2,3],
                [4,5,6]])
np.concatenate([a2,a2],axis = 1) #옆으로 붙는다. axis값을 다르게 줌으로써 확인가능\

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [133]:
#vstack() : 수직 스택, 1차원으로 연결
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [134]:
#hstack() #수평으로 2차원 배열 연결
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [135]:
#dstack() : 깊이 스택, 3차원으로 연결
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [136]:
#stack() : 새로운 차원으로 연결
np.stack([a2,a2]) #2차원이 3차원으로 차원이 바뀌어서 표현되었다. 

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

배열 분할

In [139]:
#split() : 배열 분할
a1 = np.arange(0,10)
print(a1)
b1, c1 = np.split(a1 , [5]) #스플릿되는 인덱스의 위치를 기반으로 
print(b1,c1)

b1 ,c1,d1,e1,f1 = np.split(a1,[2,4,6,8]) #스플릿되는 읻겟의 위치를 여러게 지정할 수도 있다. 
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


In [140]:
#vsplit() : 수직 분할,1차원으로 분할
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.vsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [141]:
#hsplit() : 수평분할, 2차원으로 분할
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.hsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [147]:
#dsplit() : 깊이분할(depth split),3차원으로 분할
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3 = np.dsplit(a3,[2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


배열 연산  
벡터화 연산을 사용한다.  
배열 요소에 대한 반복적인 계산을 효율적으로 수행  
numpy의 범용함수를 통해 구현  


In [150]:
#브로드 캐스팅 : 배열의 크기가 서로 다르더라도 동일한 값이 모든 요소에 연산된다. 
a1 = np.array([1,2,3])
print(a1)
print(a1+5)
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a1 + a2) #서로 차원이 달라도 연산이 가능하다.

b2 = np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1+b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


산술연산  

In [151]:
a1 = np.arange(1,10)
print(a1)
print(a1+1)


[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]


In [164]:
print(np.add(a1,10))
print(a1 - 2)
print(np.subtract(a1,10)) #범용함수
print(-a1)
print(np.negative(a1))

print(a1*2)
print(np.multiply(a1,2))

print(a1 / 2)
print(np.divide(a1,2))

print(a1//2)
print(np.floor_divide(a1,2)) #내림 나눗셈을 한다. 

print(a1**2)
print(np.power(a1,2)) #지수

print(a1%2)
print(np.mod(a1,2)) #나머지 


[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [169]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1,10, size = 9)
print(b1)

print(a1+b1)
print(a1-b1)
print(a1*b1)
print(a1/b1)
print(a1//b1)
print(a1**b1)
print(a1%b1)

[1 2 3 4 5 6 7 8 9]
[8 2 7 7 9 7 6 5 3]
[ 9  4 10 11 14 13 13 13 12]
[-7  0 -4 -3 -4 -1  1  3  6]
[ 8  4 21 28 45 42 42 40 27]
[0.125      1.         0.42857143 0.57142857 0.55555556 0.85714286
 1.16666667 1.6        3.        ]
[0 1 0 0 0 0 1 1 3]
[      1       4    2187   16384 1953125  279936  117649   32768     729]
[1 0 3 4 5 6 1 3 0]


In [171]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10,size=(3,3))
print(b2)

print(a2+b2)
print(a2-b2)
print(a2*b2)
print(a2/b2)
print(a2//b2)
print(a2**b2)
print(a2%b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[6 1 3]
 [8 4 6]
 [3 9 2]]
[[ 7  3  6]
 [12  9 12]
 [10 17 11]]
[[-5  1  0]
 [-4  1  0]
 [ 4 -1  7]]
[[ 6  2  9]
 [32 20 36]
 [21 72 18]]
[[0.16666667 2.         1.        ]
 [0.5        1.25       1.        ]
 [2.33333333 0.88888889 4.5       ]]
[[0 2 1]
 [0 1 1]
 [2 0 4]]
[[        1         2        27]
 [    65536       625     46656]
 [      343 134217728        81]]
[[1 0 0]
 [4 1 0]
 [1 8 1]]


In [173]:
#절댓값 함수
#abs()
a1 = np.random.randint(-10,10,size =5)
print(a1)
print(np.abs(a1))

[-3  9 -3 -9 -6]
[3 9 3 9 6]


In [174]:
#제곱.제곱근 함수sqrt()
print(a1)
print(np.sqrt(a1))

[-3  9 -3 -9 -6]
[nan  3. nan nan nan]


지수와 로그함수

In [175]:
a1 = np.random.randint(1,10,size = 5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[5 4 9 5 8]
[ 148.4131591    54.59815003 8103.08392758  148.4131591  2980.95798704]
[ 32.  16. 512.  32. 256.]
[25 16 81 25 64]


In [176]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[5 4 9 5 8]
[1.60943791 1.38629436 2.19722458 1.60943791 2.07944154]
[2.32192809 2.         3.169925   2.32192809 3.        ]
[0.69897    0.60205999 0.95424251 0.69897    0.90308999]


In [178]:
#삼각함수
#sin,cos,tan,arcsin,sinh,deg2rad , rad2deg etc..
t = np.linspace(0,np.pi,3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [179]:
x = [-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


집계함수  

In [182]:
#NaN안전 모드 : not a number의미 숫자가 아닌 어떤 값이 떴을 때, 안전모드로 에러를 제외하면서 안전하게 수행되도록 한다. 
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis = 0), np.sum(a2,axis = 0))
print(a2.sum(axis = 1), np.sum(a2,axis = 1))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
55 55
[18 22 15] [18 22 15]
[15 14 26] [15 14 26]


In [183]:
print(a2)
print( np.cumsum(a2))
print( np.cumsum(a2,axis = 0))
print( np.cumsum(a2,axis = 1))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
[ 7 12 15 17 26 29 38 46 55]
[[ 7  5  3]
 [ 9 14  6]
 [18 22 15]]
[[ 7 12 15]
 [ 2 11 14]
 [ 9 17 26]]


In [184]:
#diff() : 차분계산
print(a2)
print( np.diff(a2))
print( np.diff(a2,axis = 0))
print( np.diff(a2,axis = 1))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
[[-2 -2]
 [ 7 -6]
 [-1  1]]
[[-5  4  0]
 [ 7 -1  6]]
[[-2 -2]
 [ 7 -6]
 [-1  1]]


In [185]:
print(a2)
print( np.prod(a2))
print( np.prod(a2,axis = 0))
print( np.prod(a2,axis = 1))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
3674160
[126 360  81]
[105  54 648]


In [186]:
print(a2)
print( np.cumprod(a2))
print( np.cumprod(a2,axis = 0))
print( np.cumprod(a2,axis = 1))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
[      7      35     105     210    1890    5670   51030  408240 3674160]
[[  7   5   3]
 [ 14  45   9]
 [126 360  81]]
[[  7  35 105]
 [  2  18  54]
 [  9  72 648]]


In [187]:
#dot()/matmul() : 점곱, 행렬곱 계산
print(a2)
b2 = np.ones_like(a2)
print(b2)
print( np.dot(a2,b2))
print( np.matmul(a2,b2))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[15 15 15]
 [14 14 14]
 [26 26 26]]
[[15 15 15]
 [14 14 14]
 [26 26 26]]


In [188]:
#tensordot() : 텐서곱 게산
print(a2)
print(b2)
print(np.tensordot(a2,b2))
print(np.tensordot(a2,b2,axes = 0))
print(np.tensordot(a2,b2,axes = 1))
#axes = 0 축에따라서 다 곱한 결과이다. 
#axes = 1 dot()과 같은 결과

[[7 5 3]
 [2 9 3]
 [9 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
55
[[[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]]
[[15 15 15]
 [14 14 14]
 [26 26 26]]


In [189]:
#cross() :벡터곱
x = [1,2,3]
y = [4,5,6]
print(np.cross(x,y))

[-3  6 -3]


In [190]:
#inner() / outer() : 내적/외적
print(a2)
print(b2)
print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[15 15 15]
 [14 14 14]
 [26 26 26]]
[[7 7 7 7 7 7 7 7 7]
 [5 5 5 5 5 5 5 5 5]
 [3 3 3 3 3 3 3 3 3]
 [2 2 2 2 2 2 2 2 2]
 [9 9 9 9 9 9 9 9 9]
 [3 3 3 3 3 3 3 3 3]
 [9 9 9 9 9 9 9 9 9]
 [8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9]]


In [191]:
#mean() : 평균 계산
print(a2) 
print(np.mean(a2))
print(np.mean(a2,axis = 0))
print(np.mean(a2 , axis=1))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
6.111111111111111
[6.         7.33333333 5.        ]
[5.         4.66666667 8.66666667]


In [192]:
#var() : 분산 계산

print(a2) 
print(np.var(a2))
print(np.var(a2,axis = 0))
print(np.var(a2 , axis=1))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
7.432098765432098
[8.66666667 2.88888889 8.        ]
[2.66666667 9.55555556 0.22222222]


In [193]:
#min() : 최소값

print(a2) 
print(np.min(a2))
print(np.min(a2,axis = 0))
print(np.min(a2 , axis=1))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
2
[2 5 3]
[3 2 8]


In [194]:
#max()
print(a2) 
print(np.max(a2))
print(np.max(a2,axis = 0))
print(np.max(a2 , axis=1))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
9
[9 9 9]
[7 9 9]


In [195]:
#argmin() : 최소값의 인덱스 출력

print(a2) 
print(np.argmin(a2))
print(np.argmin(a2,axis = 0))
print(np.argmin(a2 , axis=1))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
3
[1 0 0]
[2 0 1]


In [196]:
#argmax() : 최댓값의 인덱스

print(a2) 
print(np.argmax(a2))
print(np.argmax(a2,axis = 0))
print(np.argmax(a2 , axis=1))

[[7 5 3]
 [2 9 3]
 [9 8 9]]
4
[2 1 2]
[0 1 0]


In [197]:
#median() : 중앙값
print(a2) 
print(np.median(a2))
print(np.median(a2,axis = 0))
print(np.median(a2 , axis=1))
#요소 값들 중 중앙 값이 무엇인지 평균과 다르다. 

[[7 5 3]
 [2 9 3]
 [9 8 9]]
7.0
[7. 8. 3.]
[5. 3. 9.]


In [198]:
#percentile() : 백분위 수
a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='linear'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='higher'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='lower'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='nearest'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


In [199]:
#any() : 
a2 = np.array([[False,False,False],
                [False,True,True],
                [False,True,True]])
print(a2)
print(np.any(a2))
print(np.any(a2,axis = 0))
print(np.any(a2,axis=1))
#전체중에 하나라도 True가 존재하면 True를 리턴한다. 

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


In [201]:
#all() : 
a2 = np.array([[False,False,False],
                [True,True,True],
                [False,True,True]])
print(a2)
print(np.all(a2))
print(np.all(a2,axis = 0))
print(np.all(a2,axis=1))
#전체가 True여야만 True를 리턴한다. 

[[False False False]
 [ True  True  True]
 [False  True  True]]
False
[False False False]
[False  True False]


In [206]:
#비교연산(Comparison operation)
a1 = np.arange(1,10)
print(a1)
print(a1 == 5) #전부를 비교하고 결괏값을 리턴시켜준다. 
print(a1 != 5)
print(a1<5)
print(a1<=5)
print(a1>5)
print(a1>=5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [209]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)

print(np.sum(a2))
print(np.count_nonzero(a2>5))
print(np.sum(a2>5)) #더하는게 아니라, 조건부합하는 경우를 카운트해줌
print(np.sum(a2>5,axis = 0))
print(np.sum(a2>5 , axis=1))

print(np.any(a2>5))
print(np.any(a2>5,axis=0))
print(np.any(a2>5,axis=1))

print(np.all(a2>5))
print(np.all(a2>5,axis=0))
print(np.all(a2>5,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


In [210]:
#isclose()
a1 = np.array([1,2,3,4,5])
print(a1)
b1 = np.array([1,2,3,3,4])
print(b1)
print(np.isclose(a1,b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [215]:
a1=np.array([np.nan,2, np.inf,4,np.NINF])
print(a1)
print(np.isnan(a1)) #Nan판별
print(np.isinf(a1))  #무한대판별
print(np.isfinite(a1)) #무한대가 아닌것만


[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


In [218]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)

print((a2>5) & (a2<8))
print(a2[(a2>5) & (a2<8)]) #True인 부분에 대한 값이 출력된다. 

print((a2>5) | (a2<8))
print(a2[(a2>5) | (a2<8)]) #True인 부분에 대한 값이 출력된다. 

print((a2>5) ^ (a2<8)) #XOR표기이다. 
print(a2[(a2>5) ^ (a2<8)]) #True인 부분에 대한 값이 출력된다. 

print(~(a2>5)) #NOT표기
print(a2[~(a2>5)]) #True인 부분에 대한 값이 출력된다. 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


In [220]:
#배열 정렬
a1 = np.random.randint(1,10,size = 10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1)) #어느 위치의 값이 와야하는지 인덱스를 나타내준다. 
print(a1)

a1.sort()
print(a1)

[1 5 3 4 4 5 9 6 9 8]
[1 3 4 4 5 5 6 8 9 9]
[1 5 3 4 4 5 9 6 9 8]
[0 2 3 4 1 5 7 9 6 8]
[1 5 3 4 4 5 9 6 9 8]
[1 3 4 4 5 5 6 8 9 9]


In [222]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(np.sort(a2,axis=0))
print(np.sort(a2,axis=1))

[[7 2 9]
 [3 5 9]
 [8 7 3]]
[[3 2 3]
 [7 5 9]
 [8 7 9]]
[[2 7 9]
 [3 5 9]
 [3 7 8]]


In [227]:
#부분 정렬 partition() :배열에서 k개의 작은 값을 반환
a1 = np.random.randint(1,10,size = 10)
print(a1)
print(np.partition(a1,3)) #세번째 인덱스까지 작은값을 반환

[2 9 4 6 7 1 6 5 6 8]
[1 2 4 5 6 6 6 7 9 8]


In [230]:
a2 = np.random.randint(1,10,size=(5,5))
print(a2)
print(np.partition(a2,3))
print(np.partition(a2,3,axis = 0))
print(np.partition(a2,3,axis=1))

[[5 9 7 3 7]
 [4 8 8 4 4]
 [3 1 6 9 6]
 [8 8 3 4 3]
 [1 8 9 5 1]]
[[3 5 7 7 9]
 [4 4 4 8 8]
 [1 3 6 6 9]
 [3 3 4 8 8]
 [1 1 5 8 9]]
[[1 8 3 4 3]
 [3 1 6 3 1]
 [4 8 7 4 4]
 [5 8 8 5 6]
 [8 9 9 9 7]]
[[3 5 7 7 9]
 [4 4 4 8 8]
 [1 3 6 6 9]
 [3 3 4 8 8]
 [1 1 5 8 9]]


In [231]:
#배열 입출력
#save(),savez(),load(),loadtxt(),savetxt()
a2 = np.random.randint(1,10,size = (5,5))
print(a2)
np.save("a",a2)

[[4 8 7 8 3]
 [6 6 1 8 6]
 [6 3 2 8 5]
 [6 6 8 1 1]
 [5 4 8 5 3]]


In [233]:
ls
#한글파일명으로 된 디렉토리는 못 읽어온다. 

 C ����̺��� �������� �̸��� �����ϴ�.
 ���� �Ϸ� ��ȣ: 9ED5-0E20

 c:\Users\User\Desktop\�ر�\�ڵ�\python\numpy ���͸�

2021-02-03  ���� 02:18    <DIR>          .
2021-02-03  ���� 02:18    <DIR>          ..
2021-02-03  ���� 02:18               228 a.npy
2021-02-01  ���� 10:01            57,990 numpyclass.ipynb
               2�� ����              58,218 ����Ʈ
               2�� ���͸�  69,819,244,544 ����Ʈ ����


In [234]:
b2 = np.random.randint(1,10,size = (5,5))
print(b2)
np.savez("ab",a2,b2)

[[2 9 7 6 8]
 [6 6 6 7 2]
 [1 8 1 1 7]
 [8 3 7 1 6]
 [7 2 3 5 3]]


In [235]:
!ls

'ls'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.


In [236]:
npy = np.load("a.npy")
print(npy)

[[4 8 7 8 3]
 [6 6 1 8 6]
 [6 3 2 8 5]
 [6 6 8 1 1]
 [5 4 8 5 3]]


In [239]:
npz = np.load("ab.npz")
print(npz.files) #npz파일 안에 저장되어 있는 배열을 확인할 수 있다. 
print(npz['arr_0'])
print(npz['arr_1']) #이름으로 접근해야 한다. 

['arr_0', 'arr_1']
[[4 8 7 8 3]
 [6 6 1 8 6]
 [6 3 2 8 5]
 [6 6 8 1 1]
 [5 4 8 5 3]]
[[2 9 7 6 8]
 [6 6 6 7 2]
 [1 8 1 1 7]
 [8 3 7 1 6]
 [7 2 3 5 3]]


In [241]:
print(a2) #binary가 아닌 텍스트로 저장하고 싶을때
np.savetxt("a.csv",a2,delimiter=',') #delimiter :구분자이다. 

[[4 8 7 8 3]
 [6 6 1 8 6]
 [6 3 2 8 5]
 [6 6 8 1 1]
 [5 4 8 5 3]]


In [242]:
!ls

'ls'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.


In [244]:
!cat a.csv

SyntaxError: invalid syntax (<ipython-input-244-1da49f54b8d8>, line 1)

In [245]:
csv = np.loadtxt("a.csv",delimiter = ',')
print(csv)

[[4. 8. 7. 8. 3.]
 [6. 6. 1. 8. 6.]
 [6. 3. 2. 8. 5.]
 [6. 6. 8. 1. 1.]
 [5. 4. 8. 5. 3.]]


In [246]:
print(b2)
np.savetxt("b.csv",b2,delimiter=',', fmt='%.2e',header='c1,c2,c3,c4,c5')
#여러가지 포맷을 적용시킬 수 있다. 

[[2 9 7 6 8]
 [6 6 6 7 2]
 [1 8 1 1 7]
 [8 3 7 1 6]
 [7 2 3 5 3]]


In [247]:
csv = np.loadtxt("b.csv",delimiter=',')
print(csv)

[[2. 9. 7. 6. 8.]
 [6. 6. 6. 7. 2.]
 [1. 8. 1. 1. 7.]
 [8. 3. 7. 1. 6.]
 [7. 2. 3. 5. 3.]]


numpy.org의 documantation을 확인하면서 기능을 확인가능하다. 