
# pandas
데이터를 처리하고 분석하는데에 활용  
데이터 프레임의 개체 삽입, 삭제에 용이  
group-by함수 제공  
csv,엑셀등의 데이터 저장,로드  
시계열 데이터를 잘 다루는 (날짜 범위 생성 및 주파수 변환), 날짜 이동 및 지연  


In [1]:
import numpy as np
import pandas as pd
pd.__version__

'1.2.1'

In [2]:
#객체 (series객체)

s = pd.Series([0,0.25,0.5,0.75,1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [3]:
s.values #값만 관찰

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
s.index #range index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s[1] #개별 요소에 접근 가능

0.25

In [6]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [13]:
s = pd.Series([0,0.25,0.5,0.75,1.0],
                index = ['a','b','c','d','e'])
s #인덱스가 변화한다. 

NameError: name 'pd' is not defined

In [8]:
s['c'] #c라는 인덱스로 접근 가능하다. 

0.5

In [9]:
s[['c','d','e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [10]:
'b' in s #인덱스의 유무도 확인 가능

True

In [11]:
s = pd.Series([0,0.25,0.5,0.75,1.0],
                index = [2,4,6,8,10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [12]:
s[4]

0.25

In [13]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [14]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
s.value_counts() #값이 각각 몇개있는지 카운트 가능

1.00    1
0.75    1
0.50    1
0.25    1
0.00    1
dtype: int64

In [16]:
s.isin([0.25,0.75]) #이 값이 어디 있는지를 확인할 수도 있다. 

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [17]:
pop_tuple = {'서울특별시':9720846,
            '부산광역시':3404423,
            '인천광역시':2947217,
            '대구광역시':2427954,
            '대전광역시':1471040,
            '광주광역시':1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [18]:
population['서울특별시']

9720846

In [19]:
population['서울특별시':'인천광역시'] #슬라이싱 가능

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

In [20]:
#DataFrame 객체 (여러 컬럼이 들어간 이차원 특성을 가질 수 있다 )
pd.DataFrame([{'A':2,'B':4,'D':3},{'A':4, 'B':5,'C':7}])#dictionary 자료형
#missingvalue값을 알아서 포함시켜준다. (Not a number)

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [21]:
pd.DataFrame(np.random.rand(5,5),
            columns=['A','B','C','D','E'],
            index=[1,2,3,4,5])

A         B         C         D         E
1  0.536339  0.188850  0.315874  0.319906  0.698423
2  0.188387  0.888141  0.744402  0.959397  0.236837
3  0.869578  0.673209  0.536249  0.356601  0.107342
4  0.386533  0.246720  0.151893  0.790216  0.024599
5  0.416939  0.518585  0.025022  0.959348  0.922722

In [22]:
male_tuple = {'서울특별시':4732275,
            '부산광역시':1668618,
            '인천광역시':1476813,
            '대구광역시':1198815,
            '대전광역시':734441,
            '광주광역시':720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [23]:
female_tuple = {'서울특별시':4988571,
            '부산광역시':1735805,
            '인천광역시':1470404,
            '대구광역시':1229139,
            '대전광역시':736599,
            '광주광역시':734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [24]:
korea_df = pd.DataFrame({'인구수':population,
                        '남자인구수':male,
                        '여자인구수':female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [25]:
korea_df = pd.DataFrame([population,male,female],columns=['인구수','남자인구수','여자인구수'])
korea_df

인구수  남자인구수  여자인구수
0  NaN    NaN    NaN
1  NaN    NaN    NaN
2  NaN    NaN    NaN

In [26]:
korea_df.index

RangeIndex(start=0, stop=3, step=1)

In [27]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [28]:
korea_df['여자인구수']

0   NaN
1   NaN
2   NaN
Name: 여자인구수, dtype: float64

In [32]:
#index 객체, index를 다루는 여러가지 방법

idx = pd.Index([2,4,6,8,10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [34]:
idx[1]

4

In [36]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [38]:
idx[-1::]

Int64Index([10], dtype='int64')

In [40]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [42]:
print(idx)
print(idx.size)
print(idx.shape) #1차원 을 가지는 구나를 알 수 있다. 
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


In [44]:
#index 연산

idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])
print(idx1)
print(idx2)
print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2) #실제 값들을 뺀 결괏값을 보여주므로 difference함수와는 다르다. 
print(idx1.intersection(idx2)) #교집합
print(idx1 & idx2)
print(idx1.union(idx2)) #중복값 제외 병합
print(idx1 | idx2) #합집합
print(idx1.delete(0)) #첫번째 인덱스 제거
print(idx1.drop(1)) #요소값을 받아서 제거
print(idx1 ^ idx2) #여집합


Int64Index([1, 2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


In [46]:
#인덱싱
s = pd.Series([0,0.25,0.5,0.75,1.0],
                index=['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [48]:
s['b']

0.25

In [50]:
'b' in s

True

In [52]:
s.keys() #인덱스 값 알려줌

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [54]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0), ('f', 1.25)]

In [56]:
s['f'] = 1.25 #추가할 인덱스를 지정해주면 값이 추가된다. 
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [58]:
s['a' : 'd'] #슬라이싱

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [60]:
s[0:4] #숫자로도 동일한 결과 출력 가능

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [62]:
s[ (s>0.4) & (s<0.8)] #조건을 주고 해당하는 것만 출력할 수도 있다. 

c    0.50
d    0.75
dtype: float64

In [91]:
#Series 인덱싱

s = pd.Series(['a','b','c','d','e'],
                index=[1,3,5,7,9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [92]:
s[1] #내가 지정한 인덱스를 쓰는 방식으로 호출

'a'

In [93]:
s[2:4]

5    c
7    d
dtype: object

In [94]:
s.iloc[1] #0부터 시작해서 내가 인덱스의 순서대로 번호가 부여된다. 

'b'

In [95]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [96]:
s.reindex(range(10)) #새로운 인덱스로 구축을 해버렸다. 

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [97]:
s.reindex(range(10),method='bfill')
#전에 있는 값으로 채워줘라는 method (backfill)

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

In [98]:
#DataFrame 인덱싱 컬럼선택, at, iloc, etc...

korea_df

인구수  남자인구수  여자인구수  남녀비율
0  NaN    NaN    NaN   NaN
1  NaN    NaN    NaN   NaN
2  NaN    NaN    NaN   NaN

In [99]:
korea_df['남자인구수']

0   NaN
1   NaN
2   NaN
Name: 남자인구수, dtype: float64

In [100]:
korea_df.남자인구수 #이런식으로도 columns에 접근할 수 있다. 

0   NaN
1   NaN
2   NaN
Name: 남자인구수, dtype: float64

In [101]:
korea_df.여자인구수

0   NaN
1   NaN
2   NaN
Name: 여자인구수, dtype: float64

In [102]:
korea_df['남녀비율'] = ((korea_df.남자인구수)*100)/korea_df.여자인구수
#새로운 columns추가했다. 

In [103]:
korea_df

인구수  남자인구수  여자인구수  남녀비율
0  NaN    NaN    NaN   NaN
1  NaN    NaN    NaN   NaN
2  NaN    NaN    NaN   NaN

In [104]:
korea_df.values #값들만 배열형태로 나타낼 수도 있다. 

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [105]:
korea_df.T #전치행렬

0   1   2
인구수   NaN NaN NaN
남자인구수 NaN NaN NaN
여자인구수 NaN NaN NaN
남녀비율  NaN NaN NaN

In [106]:
korea_df.values[0]

array([nan, nan, nan, nan])

In [107]:
korea_df['인구수']

0   NaN
1   NaN
2   NaN
Name: 인구수, dtype: float64

In [108]:
korea_df.loc[:'인천광역시',:'남자인구수']
#행과열을 각각 따로 슬라이싱할 수 있다. 

인구수  남자인구수
0  NaN    NaN
1  NaN    NaN
2  NaN    NaN

In [109]:
korea_df.loc[(korea_df.여자인구수)>1000000]
 #조건에 해당하는 값들만 출력

Empty DataFrame
Columns: [인구수, 남자인구수, 여자인구수, 남녀비율]
Index: []

In [110]:
korea_df.loc[(korea_df.인구수)<2000000]

Empty DataFrame
Columns: [인구수, 남자인구수, 여자인구수, 남녀비율]
Index: []

In [111]:
korea_df.loc[(korea_df.인구수)>2500000]

Empty DataFrame
Columns: [인구수, 남자인구수, 여자인구수, 남녀비율]
Index: []

In [112]:
korea_df.loc[korea_df.남녀비율 > 100]

Empty DataFrame
Columns: [인구수, 남자인구수, 여자인구수, 남녀비율]
Index: []

In [113]:
korea_df.loc[(korea_df.인구수>2500000) & (korea_df.남녀비율>100)]

Empty DataFrame
Columns: [인구수, 남자인구수, 여자인구수, 남녀비율]
Index: []

In [114]:
korea_df.iloc[:3,:2]
#정수 색인을 사용하는 방식 integer location

인구수  남자인구수
0  NaN    NaN
1  NaN    NaN
2  NaN    NaN

In [115]:
#다중 인덱싱 3차원 4차원 이상의 고차원 데이터 처리
#단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

korea_df

인구수  남자인구수  여자인구수  남녀비율
0  NaN    NaN    NaN   NaN
1  NaN    NaN    NaN   NaN
2  NaN    NaN    NaN   NaN

In [116]:
idx_tuples = [('서울특별시',2010),('서울특별시',2020),
                ('부산광역시',2010),('부산광역시',2020),
                ('인천광역시',2010),('인천광역시',2020),
                ('대구광역시',2010),('대구광역시',2020),
                ('대전광역시',2010),('대전광역시',2020),
                ('광주광역시',2010),('광주광역시',2020),]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [118]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [119]:
pop_tuples = [10312545,9720846,
            3567910,3404423,
            2758296,2947217,
            2511676,2427954,
            1503664,1471040,
            1454636,1455048 ]
population = pd.Series(pop_tuples, index=midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [120]:
population = population.reindex(midx)
population
#멀티인덱싱을 한 후에 구분을 시켜줄 수 있다. 

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [121]:
population[:,2010] #2010년도 것만 보여줘라는 의미이다. 

서울특별시    10312545
부산광역시     3567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [122]:
population['대전광역시',:] #년도 두개에 대한 대전광역시의 인구

2010    1503664
2020    1471040
dtype: int64

In [123]:
korea_mdf = population.unstack() #멀티인덱싱을 해 놓은 객체를 데이터 프레임으로 바꿔주는 함수
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   3567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [124]:
korea_mdf.stack()
#멀티인덱스를 가지는 데이터 프레임을 다시 시리즈로 변환해주는 함수

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     3567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [125]:
male_tuples = [5111259,4732275,
            1773170,1668618,
            1390356, 1476813,
            1255245, 1198815,
            753648, 734441,
            721780, 720060]
male_tuples

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [126]:
korea_mdf = pd.DataFrame({"총인구수":population,
                        '남자인구수':male_tuples})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   3567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [127]:
female_tuples = [5201286,4988571,
                1794740,1735805,
                1367940, 1470404,
                1256431, 1229139,
                750016, 736599,
                732856,734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [128]:
korea_mdf = pd.DataFrame({'총인구수' : population, '남자인구수' : male_tuples, '여자인구수':female_tuples})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   3567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [129]:
ratio = korea_mdf['남자인구수']*100/korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [130]:
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [131]:

korea_mdf = pd.DataFrame({'총인구수' : population, '남자인구수' : male_tuples, '여자인구수':female_tuples,'남녀비율':ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [132]:
#다중인덱스 생성
df = pd.DataFrame(np.random.rand(6,3),
                index=[['a','a','b','b','c','c'],[1,2,1,2,1,2]],
                columns=['c1','c2','c3'])
df #인덱스가 중복되지만 멀티인덱스로 표현된다. 

c1        c2        c3
a 1  0.680282  0.625151  0.788578
  2  0.744944  0.655773  0.778082
b 1  0.928939  0.584801  0.184736
  2  0.563530  0.458541  0.907022
c 1  0.913727  0.221524  0.726608
  2  0.194488  0.357718  0.394133

In [133]:
pd.MultiIndex.from_arrays([['a','a','b','b','c','c'],[1,2,1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [134]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2),('c',1),('c',2)])
#대상이 array인지 tuple인지에 따라 from_XX의 함수가 달라진다. 

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [135]:
pd.MultiIndex.from_product([['a','b','c'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [136]:
pd.MultiIndex(levels=[['a','b','c'],[1,2]],
            codes=[[0,0,1,1,2,2],[0,1,0,1,0,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [137]:
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [138]:
population.index.names = ['행정구역','년도']
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [139]:
idx = pd.MultiIndex.from_product([['a','b','c'],[1,2]],names=['name1','name2'])
cols = pd.MultiIndex.from_product([['c1','c2','c3'],[1,2]],
                    names=['col_name1','col_name2'])
data = np.round(np.random.randn(6,6),2) #소숫점 이하 2번째 자리까지 반올림
mdf = pd.DataFrame(data,index=idx,columns=cols)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -1.11 -0.34 -0.37 -0.85  1.32 -0.97
      2     -0.27 -0.26 -1.28 -1.70 -0.95 -0.33
b     1      0.99 -1.09 -1.26  0.75 -0.59 -0.74
      2      0.03  0.76  1.87  1.46 -0.34  1.34
c     1      1.55 -0.45 -0.27  0.11  0.90  0.56
      2     -0.00 -0.68  0.38  0.46  1.91  1.06

In [140]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1     -0.37 -0.85
      2     -1.28 -1.70
b     1     -1.26  0.75
      2      1.87  1.46
c     1     -0.27  0.11
      2      0.38  0.46

In [141]:
# 인덱싱 슬라이싱 
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [142]:
population['인천광역시',2010]

2758296

In [143]:
population[:,2010] #2010년도에 대한 값 출력

행정구역
서울특별시    10312545
부산광역시     3567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [144]:
population[population>3000000]

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
dtype: int64

In [145]:
population[['대구광역시','대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [147]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -1.11 -0.34 -0.37 -0.85  1.32 -0.97
      2     -0.27 -0.26 -1.28 -1.70 -0.95 -0.33
b     1      0.99 -1.09 -1.26  0.75 -0.59 -0.74
      2      0.03  0.76  1.87  1.46 -0.34  1.34
c     1      1.55 -0.45 -0.27  0.11  0.90  0.56
      2     -0.00 -0.68  0.38  0.46  1.91  1.06

In [148]:
mdf['c2',1]

name1  name2
a      1       -0.37
       2       -1.28
b      1       -1.26
       2        1.87
c      1       -0.27
       2        0.38
Name: (c2, 1), dtype: float64

In [149]:
mdf.iloc[:3,:4]

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1     -1.11 -0.34 -0.37 -0.85
      2     -0.27 -0.26 -1.28 -1.70
b     1      0.99 -1.09 -1.26  0.75

In [150]:
mdf.loc[:,('c2',1)] #c2에 첫번째에 해당하는 전체 행을 출력해줘

name1  name2
a      1       -0.37
       2       -1.28
b      1       -1.26
       2        1.87
c      1       -0.27
       2        0.38
Name: (c2, 1), dtype: float64

In [152]:
idx_slice = pd.IndexSlice #슬라이스 객체를 사용하여 그 부분만 해당하게 지정할 수도 있다.
mdf.loc[idx_slice[:,2],idx_slice[:,2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2     -0.26 -1.70 -0.33
b     2      0.76  1.46  1.34
c     2     -0.68  0.46  1.06

In [153]:
# 다중인덱스 재정렬
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [154]:
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [158]:
#korea_mdf['서울특별시':'인천광역시']
#에러 발생, 정렬이 안되어있어서
korea_mdf = korea_mdf.sort_index()
korea_mdf #가나다순으로 정렬을 해주었다. 

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [159]:
korea_mdf['광주광역시':'서울특별시']

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336

In [160]:
korea_mdf.unstack(level=0)

총인구수                                                 남자인구수           \
행정구역    광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
년도                                                                             
2010  1454636  2511676  1503664  3567910  10312545  2758296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2947217  720060  1198815   

                       ...   여자인구수                                  남녀비율  \
행정구역   대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
년도                     ...                                                 
2010  753648  1773170  ...  750016  1794740  5201286  1367940  98.488653   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                               
행정구역      대구광역시       대전광역시      부산광역시      서울특별시       인천광역시  
년도                                                             
2010  99.905606  100.484256  98.798155  98.269140  101.638668  
2020  97.532907   99.707032  96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [161]:
korea_mdf.unstack(level=1)#level에 따라 연도와 행정구역 스위치가능하다. 

총인구수             남자인구수             여자인구수                 남녀비율  \
년도         2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                       
광주광역시   1454636  1455048   721780   720060   732856   734988   98.488653   
대구광역시   2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
대전광역시   1503664  1471040   753648   734441   750016   736599  100.484256   
부산광역시   3567910  3404423  1773170  1668618  1794740  1735805   98.798155   
서울특별시  10312545  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2947217  1390356  1476813  1367940  1470404  101.638668   

                   
년도           2020  
행정구역               
광주광역시   97.968946  
대구광역시   97.532907  
대전광역시   99.707032  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [162]:
korea_mdf.stack() #원상복귀

행정구역   년도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남녀비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남녀비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남녀비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남녀비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남녀비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남녀비율     9.970703e+01
부산광역시  2010  총인구수     3.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남녀비율     9.879815e+01
 

In [11]:
korea_mdf

NameError: name 'korea_mdf' is not defined

In [164]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat #index reset

행정구역      총인구수    남자인구수    여자인구수        남녀비율
년도                                                 
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   3567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [165]:
idx_flat = korea_mdf.reset_index(level=(0,1))
idx_flat #행정구역과 년도 모두 인덱스로 구분되었다. 

행정구역    년도      총인구수    남자인구수    여자인구수        남녀비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   3567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [166]:
idx_flat.set_index(['행정구역','년도'])
#행정구역과 년도가 다시 붙는다. 

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   3567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [167]:
# 데이터 연산
s  = pd.Series(np.random.randint(0,10,5))
s

0    6
1    9
2    4
3    7
4    1
dtype: int32

In [171]:
df = pd.DataFrame(np.random.randint(0,10,9).reshape(3,3),
                columns=['A','B','C'])
df

A  B  C
0  5  5  1
1  5  5  0
2  7  5  6

In [172]:
np.exp(s)

0     403.428793
1    8103.083928
2      54.598150
3    1096.633158
4       2.718282
dtype: float64

In [173]:
np.cos(df *np.pi/4)

A         B             C
0 -0.707107 -0.707107  7.071068e-01
1 -0.707107 -0.707107  1.000000e+00
2  0.707107 -0.707107 -1.836970e-16

In [174]:
s1 = pd.Series([1,3,5,7,9],index=[0,1,2,3,4])
s2 = pd.Series([2,4,6,8,10],index=[1,2,3,4,5])
s1 + s2 #index가 기준이므로 인덱스가 같은것끼리 덧셈연산을 했다.

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [175]:
s1.add(s2,fill_value=0)
 #fill_value : Nan일 경우에 지정값으로 채워주라는 의미이다. 

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [178]:
df1 = pd.DataFrame(np.random.randint(0,10,(3,3)),
                    columns=list('ACD'))
df1

A  C  D
0  3  7  1
1  3  1  3
2  2  8  5

In [179]:
df2 = pd.DataFrame(np.random.randint(0,20,(5,5)),
                    columns=list('BAECD'))
df2

B   A   E   C   D
0  12  19  15  17   9
1  19   5  10  12   1
2  15  12  18  15   7
3  13  13   2  12  14
4   4   8  11  14   8

In [183]:
df1 + df2 #비어있는 값이 상당히 많이 존재하게 된다. 

A   B     C     D   E
0  22.0 NaN  24.0  10.0 NaN
1   8.0 NaN  13.0   4.0 NaN
2  14.0 NaN  23.0  12.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [181]:
fvalue = df1.stack().mean() #df1의 값들의 평균값
df1.add(df2,fill_value=fvalue)

A          B          C          D          E
0  22.000000  15.666667  24.000000  10.000000  18.666667
1   8.000000  22.666667  13.000000   4.000000  13.666667
2  14.000000  18.666667  23.000000  12.000000  21.666667
3  16.666667  16.666667  15.666667  17.666667   5.666667
4  11.666667   7.666667  17.666667  11.666667  14.666667

In [184]:
#연산자 범용함수
#add()
a = np.random.randint(1,10,(3,3))
a

array([[8, 6, 2],
       [3, 7, 6],
       [2, 3, 4]])

In [185]:
a + a[0]

array([[16, 12,  4],
       [11, 13,  8],
       [10,  9,  6]])

In [189]:
df = pd.DataFrame(a,columns=list('ABC'))
df

A  B  C
0  8  6  2
1  3  7  6
2  2  3  4

In [190]:
df + df.iloc[0]

A   B  C
0  16  12  4
1  11  13  8
2  10   9  6

In [191]:
df.add(df.iloc[0])

A   B  C
0  16  12  4
1  11  13  8
2  10   9  6

In [192]:
#sub() / subtract()
a

array([[8, 6, 2],
       [3, 7, 6],
       [2, 3, 4]])

In [193]:
a - a[0]

array([[ 0,  0,  0],
       [-5,  1,  4],
       [-6, -3,  2]])

In [194]:
df

A  B  C
0  8  6  2
1  3  7  6
2  2  3  4

In [195]:
df-df.iloc[0]

A  B  C
0  0  0  0
1 -5  1  4
2 -6 -3  2

In [196]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1 -5  1  4
2 -6 -3  2

In [197]:
df.subtract(df['B'],axis = 0)

A  B  C
0  2  0 -4
1 -4  0 -1
2 -1  0  1

In [198]:
#mul()
a

array([[8, 6, 2],
       [3, 7, 6],
       [2, 3, 4]])

In [199]:
a * a[0]

array([[64, 36,  4],
       [24, 42, 12],
       [16, 18,  8]])

In [200]:
df

A  B  C
0  8  6  2
1  3  7  6
2  2  3  4

In [202]:
df*df.iloc[1]

A   B   C
0  24  42  12
1   9  49  36
2   6  21  24

In [203]:
df.mul(df.iloc[1])

A   B   C
0  24  42  12
1   9  49  36
2   6  21  24

In [204]:
#truediv(),div(),divide(),floordiv()
a

array([[8, 6, 2],
       [3, 7, 6],
       [2, 3, 4]])

In [205]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [0.375     , 1.16666667, 3.        ],
       [0.25      , 0.5       , 2.        ]])

In [206]:
df

A  B  C
0  8  6  2
1  3  7  6
2  2  3  4

In [207]:
df / df.iloc[0]

A         B    C
0  1.000  1.000000  1.0
1  0.375  1.166667  3.0
2  0.250  0.500000  2.0

In [208]:
df.truediv(df.iloc[0])

A         B    C
0  1.000  1.000000  1.0
1  0.375  1.166667  3.0
2  0.250  0.500000  2.0

In [209]:
df.div(df.iloc[0])

A         B    C
0  1.000  1.000000  1.0
1  0.375  1.166667  3.0
2  0.250  0.500000  2.0

In [210]:
a//a[0]

array([[1, 1, 1],
       [0, 1, 3],
       [0, 0, 2]], dtype=int32)

In [211]:
df.floordiv(df.iloc[0]) #반올림

A  B  C
0  1  1  1
1  0  1  3
2  0  0  2

In [212]:
a % a[0]

array([[0, 0, 0],
       [3, 1, 0],
       [2, 3, 0]], dtype=int32)

In [213]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  3  1  0
2  2  3  0

In [214]:
a ** a[0] #제곱

array([[16777216,    46656,        4],
       [    6561,   117649,       36],
       [     256,      729,       16]], dtype=int32)

In [216]:
df.pow(df.iloc[0])

A       B   C
0  16777216   46656   4
1      6561  117649  36
2       256     729  16

In [217]:
row = df.iloc[0,::2]
row

A    8
C    2
Name: 0, dtype: int32

In [218]:
df-row

A   B    C
0  0.0 NaN  0.0
1 -5.0 NaN  4.0
2 -6.0 NaN  2.0

In [ ]:
#sort() , 정렬

In [4]:
git remote add origin https://github.com/JunKi-Park/Tutorial.git
git branch -M main
git push -u origin main

SyntaxError: invalid syntax (<ipython-input-4-8adc41b01fc0>, line 1)